[package]
name = "voidnet"
version = "0.1.0"
edition = "2024"

[dependencies]
errno = { version = "0.3" }
thiserror = { version = "2" }
memmap2 = { version = "0.9" }
libc = { version = "0.2" }
libxdp-sys = { git = "https://github.com/belowm/libxdp-sys.git", branch = "main" }
# libxdp-sys = { version = "0.2" } need to figure this out....
pnet = { version = "0.35" }
dashmap = { version = "6.1" }

[dev-dependencies]
clap = { version = "4.5", features = ["derive", "cargo"] }
ctrlc = { version = "3.2", features = ["termination"] }

[profile.profiling]
inherits = "release"
debug = true

[lib]
name = "libvoid"
path = "src/lib.rs"
test = true
bench = true
doctest = true
