[package]
name = "voidnet"
version = "0.1.0"
edition = "2024"

[dependencies]
dashmap = { version = "6.1", default-features = false }
errno = { version = "0.3", default-features = false }
futures-core = { version = "0.3", default-features = false, optional = true }
futures-util = { version = "0.3", default-features = false, features = [
    "std",
], optional = true }
libc = { version = "0.2", default-features = false }
libxdp-sys = { version = "=0.2.2", default-features = false } # Latest version of this library has a broken build....
memmap2 = { version = "0.9", default-features = false }
neli = { version = "0.7", default-features = false, features = ["sync"] }
smallvec = { version = "1.15", default-features = false }
async-io = { version = "2", default-features = false, optional = true }
thiserror = { version = "2", default-features = false }
tokio = { version = "1", default-features = false, features = [
    "net",
], optional = true }

[dev-dependencies]
clap = { version = "4.5", features = ["derive", "cargo"] }
criterion = { version = "0.8" }
ctrlc = { version = "3.2", features = ["termination"] }
pnet = { version = "0.35" }
rand = { version = "0.9" }
tokio = { version = "1.40", features = ["full"] }
futures = { version = "0.3" }
smol = { version = "2" }

[features]
default = []
async = ["dep:futures-core", "dep:futures-util"]
local = ["async"]
smol = ["dep:async-io", "async"]
tokio = ["dep:tokio", "async"]

[profile.profiling]
inherits = "release"
debug = true

[lib]
name = "libvoid"
path = "src/lib.rs"
test = true
bench = true
doctest = true
