[package]
name = "voidnet"
version = "0.1.0"
edition = "2024"

[dependencies]
async-io = { version = "2", default-features = false, optional = true }
coarsetime = { version = "0.1", default-features = false }
core_affinity = { version = "0.8", default-features = false }
crossbeam-queue = { version = "0.3", default-features = true }
crossbeam-utils = { version = "0.8", default-features = true }
dashmap = { version = "6.1", default-features = false }
errno = { version = "0.3", default-features = false }
futures-core = { version = "0.3", default-features = false }
futures-util = { version = "0.3", default-features = false, features = ["std"] }
getifaddrs = { version = "0.6", default-features = false }
libc = { version = "0.2", default-features = false }
libxdp-sys = { version = "=0.2.2", default-features = false } # Latest version of this library has a broken build....
memchr = { version = "2", default-features = false }
memmap2 = { version = "0.9", default-features = false }
rustc-hash = { version = "2" }
neli = { version = "0.7", default-features = false, features = ["sync"] }
slab = { version = "0.4", default-features = false }
smallvec = { version = "1.15", default-features = false }
thiserror = { version = "2", default-features = false }
tokio = { version = "1", default-features = false, features = [
    "net",
], optional = true }

[dev-dependencies]
bytes = { version = "1.11" }
clap = { version = "4.5", features = ["derive", "cargo"] }
criterion = { version = "0.8" }
ctrlc = { version = "3.2", features = ["termination"] }
futures = { version = "0.3" }
http-body-util = "0.1"
hyper = { version = "1", features = ["full"] }
hyper-util = { version = "0.1", features = ["full"] }
macro_rules_attribute = { version = "0.2" }
pnet = { version = "0.35" }
rand = { version = "0.10" }
smol = { version = "2" }
smol-macros = { version = "0.1" }
tokio = { version = "1.40", features = ["full"] }

[features]
default = []
async = []
local = ["async"]
smol = ["dep:async-io", "async"]
tokio = ["dep:tokio", "async"]

[profile.profiling]
inherits = "release"
debug = true

[lib]
name = "libvoid"
path = "src/lib.rs"
test = true
bench = true
doctest = true

[[test]]
name = "sync"
path = "tests/sync.rs"

[[test]]
name = "local"
path = "tests/local.rs"
required-features = ["local"]

[[test]]
name = "smol"
path = "tests/smol.rs"
required-features = ["smol"]

[[test]]
name = "tokio"
path = "tests/tokio.rs"
required-features = ["tokio"]

[[example]]
name = "info"
path = "examples/info.rs"

[[example]]
name = "local-rx"
path = "examples/local-rx.rs"
required-features = ["local"]

[[example]]
name = "smol-rx"
path = "examples/smol-rx.rs"
required-features = ["smol"]

[[example]]
name = "sync-rx-ms"
path = "examples/sync-rx-ms.rs"

[[example]]
name = "sync-rx"
path = "examples/sync-rx.rs"

[[example]]
name = "sync-tx-ms"
path = "examples/sync-tx-ms.rs"

[[example]]
name = "sync-tx"
path = "examples/sync-tx.rs"

[[example]]
name = "tokio-rx-ms"
path = "examples/tokio-rx-ms.rs"
required-features = ["tokio"]

[[example]]
name = "tokio-rx"
path = "examples/tokio-rx.rs"
required-features = ["tokio"]

[[example]]
name = "tokio-tx"
path = "examples/tokio-tx.rs"
required-features = ["tokio"]

[[example]]
name = "std-tcp-echo-server"
path = "examples/std-tcp-echo-server.rs"

[[example]]
name = "std-tcp-echo-client"
path = "examples/std-tcp-echo-client.rs"

[[bench]]
name = "checksum"
harness = false

[[bench]]
name = "tcp_segment"
harness = false

[[bench]]
name = "tcp_inbound"
harness = false

[[bench]]
name = "http_parse"
harness = false
