use std::mem::size_of;
use std::time::Instant;

use crate::{
    net::PmtuCache,
    xdp::frame::{Frame, FrameBuffer},
};

use super::wire::{
    ethernet::EthernetFrame,
    icmpv4::Icmpv4Codes,
    ip::{IPV4_MIN_FRAME_LEN, IpProtocols, Ipv4Header, verify_ipv4_checksum},
};
use super::{icmpv4, udp::UdpHandler};

/// Layer-3 handler for incoming IPv4 frames.
///
/// Validates the IPv4 header (version, length, checksum) and dispatches
/// to protocol-specific handlers based on the protocol field.
///
/// The frame is always consumed and pushed to exactly one buffer:
///
/// * `rx_return` -- validation failures or received data for upper layers.
/// * `tx_return` -- responses generated by protocol handlers (e.g.
///   ICMP echo reply, Destination Unreachable).
pub struct Ipv4Handler;

impl Ipv4Handler {
    pub fn new() -> Self {
        Self
    }

    /// Processes an incoming IPv4 frame.
    ///
    /// Validates the header and dispatches to the appropriate protocol
    /// handler. The frame is always consumed.
    pub fn handle<'umem>(
        &mut self,
        frame: Frame<'umem>,
        udp_handler: &mut UdpHandler<'umem>,
        pmtu: &PmtuCache,
        _now: Instant,
        _free_frames: &mut impl FrameBuffer<'umem>,
        rx_return: &mut impl FrameBuffer<'umem>,
        tx_return: &mut impl FrameBuffer<'umem>,
    ) {
        if frame.len() < IPV4_MIN_FRAME_LEN {
            eprintln!(
                "ipv4: frame too short ({} bytes, need {})",
                frame.len(),
                IPV4_MIN_FRAME_LEN,
            );
            rx_return.push(frame);
            return;
        }

        let ip = Ipv4Header::from_frame(&frame);

        if ip.version() != 4 {
            eprintln!("ipv4: unexpected version {}", ip.version());
            rx_return.push(frame);
            return;
        }

        if ip.ihl() < 5 {
            eprintln!("ipv4: IHL too small ({})", ip.ihl());
            rx_return.push(frame);
            return;
        }

        let total_length = ip.total_length() as usize;
        let header_len = ip.header_len();

        if total_length < header_len {
            eprintln!(
                "ipv4: total_length ({}) < header_len ({})",
                total_length, header_len,
            );
            rx_return.push(frame);
            return;
        }

        let eth_len = size_of::<EthernetFrame>();
        if frame.len() < eth_len + total_length {
            eprintln!(
                "ipv4: frame too short for total_length ({} bytes, need {})",
                frame.len(),
                eth_len + total_length,
            );
            rx_return.push(frame);
            return;
        }

        let ip_bytes = &frame[eth_len..eth_len + header_len];
        if !verify_ipv4_checksum(ip_bytes) {
            eprintln!("ipv4: invalid header checksum");
            rx_return.push(frame);
            return;
        }

        let protocol = ip.protocol;
        match protocol {
            IpProtocols::Icmp => icmpv4::handle_icmpv4(frame, pmtu, rx_return, tx_return),
            IpProtocols::Udp => udp_handler.process_ipv4(frame, rx_return),
            _ => icmpv4::send_destination_unreachable(
                frame,
                Icmpv4Codes::ProtocolUnreachable,
                0,
                rx_return,
                tx_return,
            ),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::net::{
        pmtu::PmtuCache,
        wire::ip::{IPV4_MIN_HEADER_LEN, IpAddress, Ipv4Address, compute_ipv4_checksum},
        wire::udp::{UDP_HEADER_LEN, compute_udp_checksum},
    };
    use crate::xdp::frame::BasicFrameBuffer;

    const REMOTE_IP: Ipv4Address = Ipv4Address::new([10, 0, 0, 2]);
    const LOCAL_IP: Ipv4Address = Ipv4Address::new([192, 168, 1, 1]);

    fn new_handler() -> Ipv4Handler {
        Ipv4Handler::new()
    }

    fn new_udp_handler<'umem>() -> UdpHandler<'umem> {
        UdpHandler::new(256)
    }

    /// Builds a minimal valid UDP segment (header only, no payload) with a
    /// correct IPv4 checksum. Ports are zero, length is 8.
    fn build_udp_bytes_v4(src: &Ipv4Address, dst: &Ipv4Address) -> Vec<u8> {
        let mut buf = vec![0u8; UDP_HEADER_LEN];
        let udp_len = UDP_HEADER_LEN as u16;
        buf[4..6].copy_from_slice(&udp_len.to_be_bytes());
        let cksum = compute_udp_checksum(src, dst, &buf);
        buf[6] = cksum[0];
        buf[7] = cksum[1];
        buf
    }

    fn new_udp_handler_with_socket<'umem>(
        port: u16,
    ) -> (
        UdpHandler<'umem>,
        crate::net::socket::LocalQueue<crate::net::ReceivedUdpPacket<'umem>>,
    ) {
        let mut udp = UdpHandler::new(256);
        let rx_queue = udp.bind(IpAddress::V4(LOCAL_IP), port, 256).unwrap();
        (udp, rx_queue)
    }

    /// Builds a valid Ethernet + IPv4 frame.
    fn build_ipv4_frame(
        src: Ipv4Address,
        dst: Ipv4Address,
        protocol: u8,
        ttl: u8,
        payload: &[u8],
    ) -> Vec<u8> {
        let total_ip_len = (IPV4_MIN_HEADER_LEN + payload.len()) as u16;
        let eth_len = size_of::<EthernetFrame>();
        let mut buf = vec![0u8; eth_len + IPV4_MIN_HEADER_LEN + payload.len()];

        buf[12] = 0x08;
        buf[13] = 0x00;

        let ip = &mut buf[14..];
        ip[0] = 0x45;
        ip[2..4].copy_from_slice(&total_ip_len.to_be_bytes());
        ip[6] = 0x40;
        ip[8] = ttl;
        ip[9] = protocol;
        let src_bytes: [u8; 4] = src.into();
        ip[12..16].copy_from_slice(&src_bytes);
        let dst_bytes: [u8; 4] = dst.into();
        ip[16..20].copy_from_slice(&dst_bytes);

        let cksum = compute_ipv4_checksum(&ip[..20]);
        ip[10] = cksum[0];
        ip[11] = cksum[1];

        buf[eth_len + IPV4_MIN_HEADER_LEN..].copy_from_slice(payload);
        buf
    }

    /// Builds a fragmented IPv4 frame.
    fn build_fragment_frame(
        src: Ipv4Address,
        dst: Ipv4Address,
        protocol: u8,
        frag_offset: u16,
        more_fragments: bool,
        payload: &[u8],
    ) -> Vec<u8> {
        let total_ip_len = (IPV4_MIN_HEADER_LEN + payload.len()) as u16;
        let eth_len = size_of::<EthernetFrame>();
        let mut buf = vec![0u8; eth_len + IPV4_MIN_HEADER_LEN + payload.len()];

        buf[12] = 0x08;
        buf[13] = 0x00;

        let ip = &mut buf[14..];
        ip[0] = 0x45;
        ip[2..4].copy_from_slice(&total_ip_len.to_be_bytes());

        let mf = if more_fragments { 0x20u8 } else { 0 };
        let hi = mf | ((frag_offset >> 8) as u8 & 0x1F);
        let lo = frag_offset as u8;
        ip[6] = hi;
        ip[7] = lo;

        ip[8] = 64;
        ip[9] = protocol;
        let src_bytes: [u8; 4] = src.into();
        ip[12..16].copy_from_slice(&src_bytes);
        let dst_bytes: [u8; 4] = dst.into();
        ip[16..20].copy_from_slice(&dst_bytes);

        let cksum = compute_ipv4_checksum(&ip[..20]);
        ip[10] = cksum[0];
        ip[11] = cksum[1];

        buf[eth_len + IPV4_MIN_HEADER_LEN..].copy_from_slice(payload);
        buf
    }

    #[test]
    fn frame_too_short_goes_to_rx() {
        let mut data = [0u8; 30];
        let mut handler = new_handler();
        let mut udp = new_udp_handler();
        let mut free = BasicFrameBuffer::new(4);
        let mut rx = BasicFrameBuffer::new(4);
        let mut tx = BasicFrameBuffer::new(4);

        let frame = Frame::new(0, &mut data, 30, false);

        handler.handle(
            frame,
            &mut udp,
            &mut PmtuCache::new(),
            Instant::now(),
            &mut free,
            &mut rx,
            &mut tx,
        );
        assert_eq!(rx.num_frames(), 1);
        assert_eq!(tx.num_frames(), 0);
    }

    #[test]
    fn wrong_version_goes_to_rx() {
        let mut data = build_ipv4_frame(REMOTE_IP, LOCAL_IP, 17, 64, &[0; 8]);
        data[14] = 0x65; // version 6 instead of 4
        let cksum = compute_ipv4_checksum(&data[14..34]);
        data[24] = cksum[0];
        data[25] = cksum[1];

        let mut handler = new_handler();
        let mut udp = new_udp_handler();
        let mut free = BasicFrameBuffer::new(4);
        let mut rx = BasicFrameBuffer::new(4);
        let mut tx = BasicFrameBuffer::new(4);

        let len = data.len();
        let frame = Frame::new(0, &mut data, len, false);

        handler.handle(
            frame,
            &mut udp,
            &mut PmtuCache::new(),
            Instant::now(),
            &mut free,
            &mut rx,
            &mut tx,
        );
        assert_eq!(rx.num_frames(), 1);
        assert_eq!(tx.num_frames(), 0);
    }

    #[test]
    fn ihl_too_small_goes_to_rx() {
        let mut data = build_ipv4_frame(REMOTE_IP, LOCAL_IP, 17, 64, &[0; 8]);
        data[14] = 0x44; // IHL = 4 (< 5)

        let mut handler = new_handler();
        let mut udp = new_udp_handler();
        let mut free = BasicFrameBuffer::new(4);
        let mut rx = BasicFrameBuffer::new(4);
        let mut tx = BasicFrameBuffer::new(4);

        let len = data.len();
        let frame = Frame::new(0, &mut data, len, false);

        handler.handle(
            frame,
            &mut udp,
            &mut PmtuCache::new(),
            Instant::now(),
            &mut free,
            &mut rx,
            &mut tx,
        );
        assert_eq!(rx.num_frames(), 1);
        assert_eq!(tx.num_frames(), 0);
    }

    #[test]
    fn bad_checksum_goes_to_rx() {
        let mut data = build_ipv4_frame(REMOTE_IP, LOCAL_IP, 17, 64, &[0; 8]);
        data[24] ^= 0xFF; // corrupt checksum

        let mut handler = new_handler();
        let mut udp = new_udp_handler();
        let mut free = BasicFrameBuffer::new(4);
        let mut rx = BasicFrameBuffer::new(4);
        let mut tx = BasicFrameBuffer::new(4);

        let len = data.len();
        let frame = Frame::new(0, &mut data, len, false);

        handler.handle(
            frame,
            &mut udp,
            &mut PmtuCache::new(),
            Instant::now(),
            &mut free,
            &mut rx,
            &mut tx,
        );
        assert_eq!(rx.num_frames(), 1);
        assert_eq!(tx.num_frames(), 0);
    }

    #[test]
    fn total_length_shorter_than_header_goes_to_rx() {
        let mut data = build_ipv4_frame(REMOTE_IP, LOCAL_IP, 17, 64, &[0; 8]);
        // Set total_length to 10 (less than 20-byte header)
        data[16] = 0x00;
        data[17] = 0x0A;
        // Recompute checksum with corrupted total_length
        data[24] = 0;
        data[25] = 0;
        let cksum = compute_ipv4_checksum(&data[14..34]);
        data[24] = cksum[0];
        data[25] = cksum[1];

        let mut handler = new_handler();
        let mut udp = new_udp_handler();
        let mut free = BasicFrameBuffer::new(4);
        let mut rx = BasicFrameBuffer::new(4);
        let mut tx = BasicFrameBuffer::new(4);

        let len = data.len();
        let frame = Frame::new(0, &mut data, len, false);

        handler.handle(
            frame,
            &mut udp,
            &mut PmtuCache::new(),
            Instant::now(),
            &mut free,
            &mut rx,
            &mut tx,
        );
        assert_eq!(rx.num_frames(), 1);
        assert_eq!(tx.num_frames(), 0);
    }

    #[test]
    fn udp_fragment_goes_to_udp_handler() {
        let mut data =
            build_fragment_frame(REMOTE_IP, LOCAL_IP, IpProtocols::Udp, 0, true, &[0; 8]);

        let mut handler = new_handler();
        let mut udp = new_udp_handler();
        let mut free = BasicFrameBuffer::new(4);
        let mut rx = BasicFrameBuffer::new(4);
        let mut tx = BasicFrameBuffer::new(4);

        let len = data.len();
        let frame = Frame::new(0, &mut data, len, false);

        handler.handle(
            frame,
            &mut udp,
            &mut PmtuCache::new(),
            Instant::now(),
            &mut free,
            &mut rx,
            &mut tx,
        );
        assert_eq!(rx.num_frames(), 0);
        assert_eq!(tx.num_frames(), 0);
        assert_eq!(udp.pending_reassembly(), 1);
    }

    #[test]
    fn non_udp_fragment_goes_to_rx() {
        // TCP fragment — dispatched via tcp_handler.process_ipv4; the
        // all-zeros payload will fail TCP header validation and the frame
        // ends up in rx_return.
        let mut data =
            build_fragment_frame(REMOTE_IP, LOCAL_IP, IpProtocols::Tcp, 0, true, &[0; 20]);

        let mut handler = new_handler();
        let mut udp = new_udp_handler();
        let mut free = BasicFrameBuffer::new(4);
        let mut rx = BasicFrameBuffer::new(4);
        let mut tx = BasicFrameBuffer::new(4);

        let len = data.len();
        let frame = Frame::new(0, &mut data, len, false);

        handler.handle(
            frame,
            &mut udp,
            &mut PmtuCache::new(),
            Instant::now(),
            &mut free,
            &mut rx,
            &mut tx,
        );
        assert_eq!(rx.num_frames(), 1);
        assert_eq!(tx.num_frames(), 0);
        assert_eq!(udp.pending_reassembly(), 0);
    }

    #[test]
    fn icmp_echo_request_generates_reply() {
        let eth_len = size_of::<EthernetFrame>();
        let icmp_len = 8 + 8;
        let ip_total = IPV4_MIN_HEADER_LEN + icmp_len;
        let frame_len = eth_len + ip_total;
        let mut data = vec![0u8; 256];

        data[12] = 0x08;
        data[13] = 0x00;
        data[14] = 0x45;
        data[16..18].copy_from_slice(&(ip_total as u16).to_be_bytes());
        data[20] = 0x40;
        data[22] = 64;
        data[23] = IpProtocols::Icmp;
        let src_bytes: [u8; 4] = REMOTE_IP.into();
        data[26..30].copy_from_slice(&src_bytes);
        let dst_bytes: [u8; 4] = LOCAL_IP.into();
        data[30..34].copy_from_slice(&dst_bytes);
        let cksum = compute_ipv4_checksum(&data[14..34]);
        data[24] = cksum[0];
        data[25] = cksum[1];

        let icmp_off = eth_len + IPV4_MIN_HEADER_LEN;
        data[icmp_off] = 8; // Echo Request
        let cksum = compute_ipv4_checksum(&data[icmp_off..icmp_off + icmp_len]);
        data[icmp_off + 2] = cksum[0];
        data[icmp_off + 3] = cksum[1];

        let mut handler = new_handler();
        let mut udp = new_udp_handler();
        let mut free = BasicFrameBuffer::new(4);
        let mut rx = BasicFrameBuffer::new(4);
        let mut tx = BasicFrameBuffer::new(4);

        let frame = Frame::new(0, &mut data, frame_len, false);
        handler.handle(
            frame,
            &mut udp,
            &mut PmtuCache::new(),
            Instant::now(),
            &mut free,
            &mut rx,
            &mut tx,
        );

        assert_eq!(rx.num_frames(), 0);
        assert_eq!(tx.num_frames(), 1);
    }

    #[test]
    fn valid_tcp_accepted() {
        let mut data = build_ipv4_frame(REMOTE_IP, LOCAL_IP, IpProtocols::Tcp, 64, &[0; 20]);

        let mut handler = new_handler();
        let mut udp = new_udp_handler();
        let mut free = BasicFrameBuffer::new(4);
        let mut rx = BasicFrameBuffer::new(4);
        let mut tx = BasicFrameBuffer::new(4);

        let len = data.len();
        let frame = Frame::new(0, &mut data, len, false);

        handler.handle(
            frame,
            &mut udp,
            &mut PmtuCache::new(),
            Instant::now(),
            &mut free,
            &mut rx,
            &mut tx,
        );
        // TCP payload is all-zeros; no valid SYN so the frame ends up in
        // rx_return (validation failure or no matching listener).
        let total = rx.num_frames() + tx.num_frames();
        assert!(
            total >= 1,
            "frame must be consumed: rx={} tx={}",
            rx.num_frames(),
            tx.num_frames()
        );
    }

    #[test]
    fn valid_udp_routed_to_socket() {
        let udp_bytes = build_udp_bytes_v4(&REMOTE_IP, &LOCAL_IP);
        let mut data = build_ipv4_frame(REMOTE_IP, LOCAL_IP, IpProtocols::Udp, 64, &udp_bytes);

        let mut handler = new_handler();
        let (mut udp, rx_queue) = new_udp_handler_with_socket(0);
        let mut free = BasicFrameBuffer::new(4);
        let mut rx = BasicFrameBuffer::new(4);
        let mut tx = BasicFrameBuffer::new(4);

        let len = data.len();
        let frame = Frame::new(0, &mut data, len, false);

        handler.handle(
            frame,
            &mut udp,
            &mut PmtuCache::new(),
            Instant::now(),
            &mut free,
            &mut rx,
            &mut tx,
        );
        assert_eq!(rx.num_frames(), 0);
        assert_eq!(tx.num_frames(), 0);
        assert_eq!(rx_queue.len(), 1);
    }

    #[test]
    fn unknown_protocol_sends_dest_unreachable() {
        let raw = build_ipv4_frame(REMOTE_IP, LOCAL_IP, 255, 64, &[0; 8]);
        let mut data = vec![0u8; 256];
        data[..raw.len()].copy_from_slice(&raw);

        let mut handler = new_handler();
        let mut udp = new_udp_handler();
        let mut free = BasicFrameBuffer::new(4);
        let mut rx = BasicFrameBuffer::new(4);
        let mut tx = BasicFrameBuffer::new(4);

        let frame = Frame::new(0, &mut data, raw.len(), false);

        handler.handle(
            frame,
            &mut udp,
            &mut PmtuCache::new(),
            Instant::now(),
            &mut free,
            &mut rx,
            &mut tx,
        );
        assert_eq!(rx.num_frames(), 0);
        assert_eq!(tx.num_frames(), 1);
    }
}
