use crate::{
    net::{
        checksum::verify_ipv4_checksum,
        wire::{
            ethernet::EthernetFrame,
            ip::{IPV4_MIN_FRAME_LEN, Ipv4Header},
        },
    },
    xdp::frame::{Frame, FrameBuffer},
};

/// Layer-3 handler for incoming IPv4 frames.
///
/// Validates the IPv4 header (version, length, checksum) and dispatches
/// to protocol-specific handlers based on the protocol field.
///
/// The frame is always consumed and pushed to exactly one buffer:
///
/// * `rx_return` -- validation failures or received data for upper layers.
/// * `tx_return` -- responses generated by protocol handlers (e.g.
///   ICMP echo reply, Destination Unreachable).
pub struct Ipv4Handler {
    rx_offload: bool,
    tx_offload: bool,
}

impl Ipv4Handler {
    pub fn new(rx_offload: bool, tx_offload: bool) -> Self {
        Self {
            rx_offload,
            tx_offload,
        }
    }

    /// Processes an incoming IPv4 frame.
    ///
    /// Validates the header and dispatches to the appropriate protocol
    /// handler. The frame is always consumed.
    pub fn handle<'umem>(
        &mut self,
        frame: Frame<'umem>,
        rx_return: &mut impl FrameBuffer<'umem>,
    ) {
        if frame.len() < IPV4_MIN_FRAME_LEN {
            rx_return.push(frame);
            return;
        }

        let ip = Ipv4Header::from_bytes(&frame);

        if ip.version() != 4 {
            rx_return.push(frame);
            return;
        }

        if ip.ihl() < 5 {
            rx_return.push(frame);
            return;
        }

        let total_length = ip.total_length() as usize;
        let header_len = ip.header_len();

        if total_length < header_len {
            rx_return.push(frame);
            return;
        }

        let eth_len = size_of::<EthernetFrame>();
        if frame.len() < eth_len + total_length {
            rx_return.push(frame);
            return;
        }

        if !self.rx_offload {
            let ip_bytes = &frame[eth_len..eth_len + header_len];
            if !verify_ipv4_checksum(ip_bytes) {
                rx_return.push(frame);
                return;
            }
        }

        rx_return.push(frame);
    }
}

#[cfg(test)]
mod tests {
    use crate::{
        net::{
            checksum::compute_ipv4_checksum,
            wire::ip::{IPV4_MIN_HEADER_LEN, Ipv4Address},
        },
        xdp::frame::BasicFrameBuffer,
    };

    use super::*;

    const REMOTE_IP: Ipv4Address = Ipv4Address::new([10, 0, 0, 2]);
    const LOCAL_IP: Ipv4Address = Ipv4Address::new([192, 168, 1, 1]);

    fn new_handler() -> Ipv4Handler {
        Ipv4Handler::new(false, false)
    }

    /// Builds a valid Ethernet + IPv4 frame.
    fn build_ipv4_frame(
        src: Ipv4Address,
        dst: Ipv4Address,
        protocol: u8,
        ttl: u8,
        payload: &[u8],
    ) -> Vec<u8> {
        let total_ip_len = (IPV4_MIN_HEADER_LEN + payload.len()) as u16;
        let eth_len = size_of::<EthernetFrame>();
        let mut buf = vec![0u8; eth_len + IPV4_MIN_HEADER_LEN + payload.len()];

        buf[12] = 0x08;
        buf[13] = 0x00;

        let ip = &mut buf[14..];
        ip[0] = 0x45;
        ip[2..4].copy_from_slice(&total_ip_len.to_be_bytes());
        ip[6] = 0x40;
        ip[8] = ttl;
        ip[9] = protocol;
        let src_bytes: [u8; 4] = src.into();
        ip[12..16].copy_from_slice(&src_bytes);
        let dst_bytes: [u8; 4] = dst.into();
        ip[16..20].copy_from_slice(&dst_bytes);

        let cksum = compute_ipv4_checksum(&ip[..20]);
        ip[10] = cksum[0];
        ip[11] = cksum[1];

        buf[eth_len + IPV4_MIN_HEADER_LEN..].copy_from_slice(payload);
        buf
    }

    #[test]
    fn frame_too_short_goes_to_rx() {
        let mut data = [0u8; 30];
        let mut handler = new_handler();
        let mut rx = BasicFrameBuffer::new(4);

        let frame = Frame::new(0, &mut data, 30, false);

        handler.handle(frame, &mut rx);
        assert_eq!(rx.num_frames(), 1);
    }

    #[test]
    fn wrong_version_goes_to_rx() {
        let mut data = build_ipv4_frame(REMOTE_IP, LOCAL_IP, 17, 64, &[0; 8]);
        data[14] = 0x65; // version 6 instead of 4
        let cksum = compute_ipv4_checksum(&data[14..34]);
        data[24] = cksum[0];
        data[25] = cksum[1];

        let mut handler = new_handler();
        let mut rx = BasicFrameBuffer::new(4);

        let len = data.len();
        let frame = Frame::new(0, &mut data, len, false);

        handler.handle(frame, &mut rx);
        assert_eq!(rx.num_frames(), 1);
    }

    #[test]
    fn ihl_too_small_goes_to_rx() {
        let mut data = build_ipv4_frame(REMOTE_IP, LOCAL_IP, 17, 64, &[0; 8]);
        data[14] = 0x44; // IHL = 4 (< 5)

        let mut handler = new_handler();
        let mut rx = BasicFrameBuffer::new(4);

        let len = data.len();
        let frame = Frame::new(0, &mut data, len, false);

        handler.handle(frame, &mut rx);
        assert_eq!(rx.num_frames(), 1);
    }

    #[test]
    fn bad_checksum_goes_to_rx() {
        let mut data = build_ipv4_frame(REMOTE_IP, LOCAL_IP, 17, 64, &[0; 8]);
        data[24] ^= 0xFF; // corrupt checksum

        let mut handler = new_handler();
        let mut rx = BasicFrameBuffer::new(4);

        let len = data.len();
        let frame = Frame::new(0, &mut data, len, false);

        handler.handle(frame, &mut rx);
        assert_eq!(rx.num_frames(), 1);
    }

    #[test]
    fn total_length_shorter_than_header_goes_to_rx() {
        let mut data = build_ipv4_frame(REMOTE_IP, LOCAL_IP, 17, 64, &[0; 8]);
        // Set total_length to 10 (less than 20-byte header)
        data[16] = 0x00;
        data[17] = 0x0A;
        // Recompute checksum with corrupted total_length
        data[24] = 0;
        data[25] = 0;
        let cksum = compute_ipv4_checksum(&data[14..34]);
        data[24] = cksum[0];
        data[25] = cksum[1];

        let mut handler = new_handler();
        let mut rx = BasicFrameBuffer::new(4);

        let len = data.len();
        let frame = Frame::new(0, &mut data, len, false);

        handler.handle(frame, &mut rx);
        assert_eq!(rx.num_frames(), 1);
    }
}
