use crate::{
    net::wire::{
        ethernet::EthernetFrame,
        ip::{
            EXT_AH, EXT_DESTINATION, EXT_FRAGMENT, EXT_HOP_BY_HOP, EXT_ROUTING,
            FRAGMENT_EXT_LEN, IPV6_HEADER_LEN, IPV6_MIN_FRAME_LEN, Ipv6Header,
            NO_NEXT_HEADER,
        },
    },
    xdp::frame::{Frame, FrameBuffer},
};

/// Result of walking IPv6 extension headers.
pub(crate) enum NextHeaderResult {
    /// Upper-layer protocol found. `protocol` is the protocol number,
    /// `payload_offset` is the byte offset from the start of the frame
    /// to the upper-layer payload, and `next_header_offset` is the byte
    /// offset of the Next Header field that contained `protocol` (used
    /// for ICMPv6 Parameter Problem pointer).
    Protocol {
        protocol: u8,
        payload_offset: usize,
        next_header_offset: usize,
    },
    /// A Fragment extension header was found, indicating this packet
    /// is fragmented. `offset` is the byte offset of the fragment
    /// extension header from the start of the frame.
    Fragment { offset: usize },
    /// The extension header chain is malformed (frame too short, etc.).
    Malformed,
    /// Reached `No Next Header` (protocol 59). The packet has no
    /// upper-layer payload.
    NoPayload,
}

/// Walks the IPv6 extension header chain starting from `next_header`
/// at byte offset `offset` (from the start of the frame).
///
/// Returns the final upper-layer protocol and its payload offset, or
/// an indication that the packet is fragmented or malformed.
///
/// Supported extension headers (skipped transparently):
/// - Hop-by-Hop Options (0)
/// - Routing (43)
/// - Destination Options (60)
/// - Authentication Header (51)
///
/// Terminal conditions:
/// - Fragment (44) -> [`NextHeaderResult::Fragment`]
/// - ESP (50) -> returned as a protocol (cannot see past encryption)
/// - No Next Header (59) -> [`NextHeaderResult::NoPayload`]
/// - Any other value -> returned as an upper-layer protocol
pub(crate) fn walk_extension_headers(
    frame: &[u8],
    mut next_header: u8,
    mut offset: usize,
    initial_nh_offset: usize,
) -> NextHeaderResult {
    const MAX_EXT_HEADERS: usize = 16;
    let mut nh_offset = initial_nh_offset;

    for _ in 0..MAX_EXT_HEADERS {
        match next_header {
            EXT_HOP_BY_HOP | EXT_ROUTING | EXT_DESTINATION => {
                if offset + 2 > frame.len() {
                    return NextHeaderResult::Malformed;
                }
                nh_offset = offset;
                let nh = frame[offset];
                let hdr_ext_len = frame[offset + 1] as usize;
                let ext_len = (hdr_ext_len + 1) * 8;
                if offset + ext_len > frame.len() {
                    return NextHeaderResult::Malformed;
                }
                next_header = nh;
                offset += ext_len;
            }
            EXT_AH => {
                if offset + 2 > frame.len() {
                    return NextHeaderResult::Malformed;
                }
                nh_offset = offset;
                let nh = frame[offset];
                let payload_len = frame[offset + 1] as usize;
                let ext_len = (payload_len + 2) * 4;
                if offset + ext_len > frame.len() {
                    return NextHeaderResult::Malformed;
                }
                next_header = nh;
                offset += ext_len;
            }
            EXT_FRAGMENT => {
                if offset + FRAGMENT_EXT_LEN > frame.len() {
                    return NextHeaderResult::Malformed;
                }
                return NextHeaderResult::Fragment { offset };
            }
            NO_NEXT_HEADER => {
                return NextHeaderResult::NoPayload;
            }
            protocol => {
                return NextHeaderResult::Protocol {
                    protocol,
                    payload_offset: offset,
                    next_header_offset: nh_offset,
                };
            }
        }
    }

    NextHeaderResult::Malformed
}

/// Layer-3 handler for incoming IPv6 frames.
///
/// Validates the IPv6 header (version, length), walks extension headers,
/// and dispatches to protocol-specific handlers.
///
/// The frame is always consumed and pushed to exactly one buffer:
///
/// * `rx_return` -- validation failures, fragmented packets, or
///   received data for upper layers.
/// * `tx_return` -- responses generated by protocol handlers (e.g.
///   ICMPv6 echo reply, Destination Unreachable).
pub struct Ipv6Handler {
    rx_offload: bool,
    tx_offload: bool,
}

impl Ipv6Handler {
    pub fn new(rx_offload: bool, tx_offload: bool) -> Self {
        Self {
            rx_offload,
            tx_offload,
        }
    }

    /// Processes an incoming IPv6 frame.
    ///
    /// Validates the header, walks extension headers, and dispatches to
    /// the appropriate protocol handler. The frame is always consumed.
    pub fn handle<'umem>(
        &mut self,
        frame: Frame<'umem>,
        rx_return: &mut impl FrameBuffer<'umem>,
    ) {
        if frame.len() < IPV6_MIN_FRAME_LEN {
            rx_return.push(frame);
            return;
        }

        let ip = Ipv6Header::from_bytes(&frame);

        if ip.version() != 6 {
            rx_return.push(frame);
            return;
        }

        let payload_length = ip.payload_length() as usize;
        let eth_len = size_of::<EthernetFrame>();

        if frame.len() < eth_len + IPV6_HEADER_LEN + payload_length {
            rx_return.push(frame);
            return;
        }

        rx_return.push(frame);
    }
}

#[cfg(test)]
mod tests {
    use crate::{
        net::wire::ip::{IpProtocols, Ipv6Address},
        xdp::frame::BasicFrameBuffer,
    };

    use super::*;

    const REMOTE_IP: Ipv6Address =
        Ipv6Address::new([0xFE, 0x80, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2]);
    const LOCAL_IP: Ipv6Address =
        Ipv6Address::new([0xFE, 0x80, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]);

    fn new_handler() -> Ipv6Handler {
        Ipv6Handler::new(false, false)
    }

    /// Builds a valid Ethernet + IPv6 frame with no extension headers.
    fn build_ipv6_frame(
        src: Ipv6Address,
        dst: Ipv6Address,
        next_header: u8,
        hop_limit: u8,
        payload: &[u8],
    ) -> Vec<u8> {
        let eth_len = size_of::<EthernetFrame>();
        let payload_len = payload.len() as u16;
        let mut buf = vec![0u8; eth_len + IPV6_HEADER_LEN + payload.len()];

        buf[12] = 0x86;
        buf[13] = 0xDD;

        let ip = &mut buf[14..];
        ip[0] = 0x60;
        ip[4..6].copy_from_slice(&payload_len.to_be_bytes());
        ip[6] = next_header;
        ip[7] = hop_limit;
        let src_bytes: [u8; 16] = src.into();
        ip[8..24].copy_from_slice(&src_bytes);
        let dst_bytes: [u8; 16] = dst.into();
        ip[24..40].copy_from_slice(&dst_bytes);

        buf[eth_len + IPV6_HEADER_LEN..].copy_from_slice(payload);
        buf
    }

    /// Builds an IPv6 frame with a Hop-by-Hop extension header.
    fn build_ipv6_with_ext_header(
        src: Ipv6Address,
        dst: Ipv6Address,
        upper_protocol: u8,
        hop_limit: u8,
        payload: &[u8],
    ) -> Vec<u8> {
        let eth_len = size_of::<EthernetFrame>();
        let ext_len = 8;
        let payload_len = (ext_len + payload.len()) as u16;
        let mut buf = vec![0u8; eth_len + IPV6_HEADER_LEN + ext_len + payload.len()];

        buf[12] = 0x86;
        buf[13] = 0xDD;

        let ip = &mut buf[14..];
        ip[0] = 0x60;
        ip[4..6].copy_from_slice(&payload_len.to_be_bytes());
        ip[6] = EXT_HOP_BY_HOP;
        ip[7] = hop_limit;
        let src_bytes: [u8; 16] = src.into();
        ip[8..24].copy_from_slice(&src_bytes);
        let dst_bytes: [u8; 16] = dst.into();
        ip[24..40].copy_from_slice(&dst_bytes);

        let ext_offset = eth_len + IPV6_HEADER_LEN;
        buf[ext_offset] = upper_protocol;
        buf[ext_offset + 1] = 0;

        buf[ext_offset + ext_len..].copy_from_slice(payload);
        buf
    }

    /// Builds an IPv6 frame with a Fragment extension header.
    fn build_ipv6_with_fragment(
        src: Ipv6Address,
        dst: Ipv6Address,
        upper_protocol: u8,
        frag_offset: u16,
        more_fragments: bool,
        payload: &[u8],
    ) -> Vec<u8> {
        let eth_len = size_of::<EthernetFrame>();
        let payload_len = (FRAGMENT_EXT_LEN + payload.len()) as u16;
        let mut buf = vec![0u8; eth_len + IPV6_HEADER_LEN + FRAGMENT_EXT_LEN + payload.len()];

        buf[12] = 0x86;
        buf[13] = 0xDD;

        let ip = &mut buf[14..];
        ip[0] = 0x60;
        ip[4..6].copy_from_slice(&payload_len.to_be_bytes());
        ip[6] = EXT_FRAGMENT;
        ip[7] = 64;
        let src_bytes: [u8; 16] = src.into();
        ip[8..24].copy_from_slice(&src_bytes);
        let dst_bytes: [u8; 16] = dst.into();
        ip[24..40].copy_from_slice(&dst_bytes);

        let frag_offset_raw = eth_len + IPV6_HEADER_LEN;
        buf[frag_offset_raw] = upper_protocol;
        buf[frag_offset_raw + 1] = 0;
        let fo_m = (frag_offset << 3) | (if more_fragments { 1 } else { 0 });
        buf[frag_offset_raw + 2..frag_offset_raw + 4].copy_from_slice(&fo_m.to_be_bytes());

        buf[frag_offset_raw + FRAGMENT_EXT_LEN..].copy_from_slice(payload);
        buf
    }

    #[test]
    fn walk_no_extensions() {
        let buf = build_ipv6_frame(REMOTE_IP, LOCAL_IP, IpProtocols::Udp, 64, &[0; 8]);
        let eth_len = size_of::<EthernetFrame>();
        let start = eth_len + IPV6_HEADER_LEN;
        let nh_offset = eth_len + 6;

        match walk_extension_headers(&buf, IpProtocols::Udp, start, nh_offset) {
            NextHeaderResult::Protocol {
                protocol,
                payload_offset,
                next_header_offset,
            } => {
                assert_eq!(protocol, IpProtocols::Udp);
                assert_eq!(payload_offset, start);
                assert_eq!(next_header_offset, nh_offset);
            }
            _ => panic!("expected Protocol"),
        }
    }

    #[test]
    fn walk_hop_by_hop_extension() {
        let buf = build_ipv6_with_ext_header(REMOTE_IP, LOCAL_IP, IpProtocols::Tcp, 64, &[0; 20]);
        let eth_len = size_of::<EthernetFrame>();
        let start = eth_len + IPV6_HEADER_LEN;
        let nh_offset = eth_len + 6;

        match walk_extension_headers(&buf, EXT_HOP_BY_HOP, start, nh_offset) {
            NextHeaderResult::Protocol {
                protocol,
                payload_offset,
                next_header_offset,
            } => {
                assert_eq!(protocol, IpProtocols::Tcp);
                assert_eq!(payload_offset, start + 8);
                assert_eq!(next_header_offset, start);
            }
            _ => panic!("expected Protocol"),
        }
    }

    #[test]
    fn walk_fragment_returns_fragment() {
        let buf = build_ipv6_with_fragment(REMOTE_IP, LOCAL_IP, IpProtocols::Udp, 0, true, &[0; 8]);
        let eth_len = size_of::<EthernetFrame>();
        let start = eth_len + IPV6_HEADER_LEN;

        match walk_extension_headers(&buf, EXT_FRAGMENT, start, eth_len + 6) {
            NextHeaderResult::Fragment { offset } => {
                assert_eq!(offset, start);
            }
            _ => panic!("expected Fragment"),
        }
    }

    #[test]
    fn walk_no_next_header() {
        let buf = build_ipv6_frame(REMOTE_IP, LOCAL_IP, NO_NEXT_HEADER, 64, &[]);
        let eth_len = size_of::<EthernetFrame>();
        let start = eth_len + IPV6_HEADER_LEN;

        match walk_extension_headers(&buf, NO_NEXT_HEADER, start, eth_len + 6) {
            NextHeaderResult::NoPayload => {}
            _ => panic!("expected NoPayload"),
        }
    }

    #[test]
    fn walk_truncated_extension_is_malformed() {
        let eth_len = size_of::<EthernetFrame>();
        let mut buf = vec![0u8; eth_len + IPV6_HEADER_LEN + 2];
        buf[12] = 0x86;
        buf[13] = 0xDD;
        buf[14] = 0x60;
        buf[18..20].copy_from_slice(&2u16.to_be_bytes());
        buf[20] = EXT_HOP_BY_HOP;
        buf[21] = 64;

        let ext_start = eth_len + IPV6_HEADER_LEN;
        buf[ext_start] = IpProtocols::Udp;
        buf[ext_start + 1] = 0; // Hdr Ext Len = 0 means 8 bytes, but only 2 available

        match walk_extension_headers(&buf, EXT_HOP_BY_HOP, ext_start, eth_len + 6) {
            NextHeaderResult::Malformed => {}
            _ => panic!("expected Malformed"),
        }
    }

    #[test]
    fn walk_exceeds_max_extensions_is_malformed() {
        // Build a chain of 17 Hop-by-Hop extension headers (exceeds MAX_EXT_HEADERS=16).
        let eth_len = size_of::<EthernetFrame>();
        let ext_count = 17;
        let ext_size = 8; // each ext header is 8 bytes (Hdr Ext Len = 0)
        let total_ext = ext_count * ext_size;
        let mut buf = vec![0u8; eth_len + IPV6_HEADER_LEN + total_ext];

        buf[12] = 0x86;
        buf[13] = 0xDD;
        buf[14] = 0x60;
        buf[18..20].copy_from_slice(&(total_ext as u16).to_be_bytes());
        buf[20] = EXT_HOP_BY_HOP;
        buf[21] = 64;

        let ext_start = eth_len + IPV6_HEADER_LEN;
        for i in 0..ext_count {
            let off = ext_start + i * ext_size;
            // Each points to Hop-by-Hop (0) as next header, except the last
            // which points to UDP (but we'll never reach it).
            buf[off] = if i < ext_count - 1 {
                EXT_HOP_BY_HOP
            } else {
                IpProtocols::Udp
            };
            buf[off + 1] = 0; // Hdr Ext Len = 0 -> 8 bytes
        }

        match walk_extension_headers(&buf, EXT_HOP_BY_HOP, ext_start, eth_len + 6) {
            NextHeaderResult::Malformed => {}
            _ => panic!("expected Malformed for excessive extension headers"),
        }
    }

    #[test]
    fn frame_too_short_goes_to_rx() {
        let mut data = [0u8; 50];

        let mut handler = new_handler();
        let mut rx = BasicFrameBuffer::new(4);

        let frame = Frame::new(0, &mut data, 50, false);

        handler.handle(frame, &mut rx);
        assert_eq!(rx.num_frames(), 1);
    }

    #[test]
    fn wrong_version_goes_to_rx() {
        let mut data = build_ipv6_frame(REMOTE_IP, LOCAL_IP, IpProtocols::Udp, 64, &[0; 8]);
        data[14] = (data[14] & 0x0F) | 0x40; // version 4 instead of 6

        let mut handler = new_handler();
        let mut rx = BasicFrameBuffer::new(4);

        let len = data.len();
        let frame = Frame::new(0, &mut data, len, false);

        handler.handle(frame, &mut rx);
        assert_eq!(rx.num_frames(), 1);
    }

    #[test]
    fn payload_shorter_than_claimed_goes_to_rx() {
        // Build a frame with only 8 bytes payload but claim 100 in payload_length
        let mut data = build_ipv6_frame(REMOTE_IP, LOCAL_IP, IpProtocols::Udp, 64, &[0; 8]);
        data[18] = 0x00;
        data[19] = 100; // claim 100 bytes but only 8 available

        let mut handler = new_handler();
        let mut rx = BasicFrameBuffer::new(4);

        let len = data.len();
        let frame = Frame::new(0, &mut data, len, false);

        handler.handle(frame, &mut rx);
        assert_eq!(rx.num_frames(), 1);
    }
}
