use coarsetime::Instant;

use crate::{
    net::{
        NeighborHandler, PmtuCache,
        wire::{
            ethernet::EthernetFrame,
            icmpv6::{Icmpv6Codes, Icmpv6Types},
            ip::{
                EXT_AH, EXT_DESTINATION, EXT_FRAGMENT, EXT_HOP_BY_HOP, EXT_ROUTING,
                FRAGMENT_EXT_LEN, IPV6_HEADER_LEN, IPV6_MIN_FRAME_LEN, IpProtocols, Ipv6Header,
                NO_NEXT_HEADER,
            },
        },
    },
    xdp::frame::{Frame, FrameBuffer},
};

use super::{icmpv6, tcp::TcpHandler, udp::UdpHandler};

/// Result of walking IPv6 extension headers.
pub(crate) enum NextHeaderResult {
    /// Upper-layer protocol found. `protocol` is the protocol number,
    /// `payload_offset` is the byte offset from the start of the frame
    /// to the upper-layer payload, and `next_header_offset` is the byte
    /// offset of the Next Header field that contained `protocol` (used
    /// for ICMPv6 Parameter Problem pointer).
    Protocol {
        protocol: u8,
        payload_offset: usize,
        next_header_offset: usize,
    },
    /// A Fragment extension header was found, indicating this packet
    /// is fragmented. `offset` is the byte offset of the fragment
    /// extension header from the start of the frame.
    Fragment { offset: usize },
    /// The extension header chain is malformed (frame too short, etc.).
    Malformed,
    /// Reached `No Next Header` (protocol 59). The packet has no
    /// upper-layer payload.
    NoPayload,
}

/// Walks the IPv6 extension header chain starting from `next_header`
/// at byte offset `offset` (from the start of the frame).
///
/// Returns the final upper-layer protocol and its payload offset, or
/// an indication that the packet is fragmented or malformed.
///
/// Supported extension headers (skipped transparently):
/// - Hop-by-Hop Options (0)
/// - Routing (43)
/// - Destination Options (60)
/// - Authentication Header (51)
///
/// Terminal conditions:
/// - Fragment (44) -> [`NextHeaderResult::Fragment`]
/// - ESP (50) -> returned as a protocol (cannot see past encryption)
/// - No Next Header (59) -> [`NextHeaderResult::NoPayload`]
/// - Any other value -> returned as an upper-layer protocol
pub(crate) fn walk_extension_headers(
    frame: &[u8],
    mut next_header: u8,
    mut offset: usize,
    initial_nh_offset: usize,
) -> NextHeaderResult {
    const MAX_EXT_HEADERS: usize = 16;
    let mut nh_offset = initial_nh_offset;

    for _ in 0..MAX_EXT_HEADERS {
        match next_header {
            EXT_HOP_BY_HOP | EXT_ROUTING | EXT_DESTINATION => {
                if offset + 2 > frame.len() {
                    return NextHeaderResult::Malformed;
                }
                nh_offset = offset;
                let nh = frame[offset];
                let hdr_ext_len = frame[offset + 1] as usize;
                let ext_len = (hdr_ext_len + 1) * 8;
                if offset + ext_len > frame.len() {
                    return NextHeaderResult::Malformed;
                }
                next_header = nh;
                offset += ext_len;
            }
            EXT_AH => {
                if offset + 2 > frame.len() {
                    return NextHeaderResult::Malformed;
                }
                nh_offset = offset;
                let nh = frame[offset];
                let payload_len = frame[offset + 1] as usize;
                let ext_len = (payload_len + 2) * 4;
                if offset + ext_len > frame.len() {
                    return NextHeaderResult::Malformed;
                }
                next_header = nh;
                offset += ext_len;
            }
            EXT_FRAGMENT => {
                if offset + FRAGMENT_EXT_LEN > frame.len() {
                    return NextHeaderResult::Malformed;
                }
                return NextHeaderResult::Fragment { offset };
            }
            NO_NEXT_HEADER => {
                return NextHeaderResult::NoPayload;
            }
            protocol => {
                return NextHeaderResult::Protocol {
                    protocol,
                    payload_offset: offset,
                    next_header_offset: nh_offset,
                };
            }
        }
    }

    NextHeaderResult::Malformed
}

/// Layer-3 handler for incoming IPv6 frames.
///
/// Validates the IPv6 header (version, length), walks extension headers,
/// and dispatches to protocol-specific handlers.
///
/// The frame is always consumed and pushed to exactly one buffer:
///
/// * `rx_return` -- validation failures, fragmented packets, or
///   received data for upper layers.
/// * `tx_return` -- responses generated by protocol handlers (e.g.
///   ICMPv6 echo reply, Destination Unreachable).
pub struct Ipv6Handler {
    rx_offload: bool,
    tx_offload: bool,
    pub(crate) ipv6_tcp_fragments_dropped: u64,
}

impl Ipv6Handler {
    pub fn new(rx_offload: bool, tx_offload: bool) -> Self {
        Self {
            rx_offload,
            tx_offload,
            ipv6_tcp_fragments_dropped: 0,
        }
    }

    /// Processes an incoming IPv6 frame.
    ///
    /// Validates the header, walks extension headers, and dispatches to
    /// the appropriate protocol handler. The frame is always consumed.
    ///
    /// NDP messages (ICMPv6 types 133-137) are dispatched to
    /// `neighbor_handler` instead of the generic ICMPv6 handler.
    pub fn handle<'umem>(
        &mut self,
        frame: Frame<'umem>,
        neighbor_handler: &NeighborHandler,
        udp_handler: &mut UdpHandler<'umem>,
        tcp_handler: &mut TcpHandler,
        pmtu: &PmtuCache,
        now: Instant,
        free_frames: &mut impl FrameBuffer<'umem>,
        rx_return: &mut impl FrameBuffer<'umem>,
        tx_return: &mut impl FrameBuffer<'umem>,
    ) {
        if frame.len() < IPV6_MIN_FRAME_LEN {
            rx_return.push(frame);
            return;
        }

        let ip = Ipv6Header::from_bytes(&frame);

        if ip.version() != 6 {
            rx_return.push(frame);
            return;
        }

        let payload_length = ip.payload_length() as usize;
        let eth_len = size_of::<EthernetFrame>();

        if frame.len() < eth_len + IPV6_HEADER_LEN + payload_length {
            rx_return.push(frame);
            return;
        }

        let first_next_header = ip.next_header;
        let ext_start = eth_len + IPV6_HEADER_LEN;
        let ip_end = ext_start + payload_length;
        let initial_nh_offset = eth_len + 6; // IPv6 Next Header field

        match walk_extension_headers(
            &frame[..ip_end],
            first_next_header,
            ext_start,
            initial_nh_offset,
        ) {
            NextHeaderResult::Protocol {
                protocol,
                payload_offset,
                next_header_offset,
            } => match protocol {
                IpProtocols::IcmpV6 => {
                    let icmpv6_len = ip_end - payload_offset;
                    icmpv6::handle_icmpv6(
                        frame,
                        payload_offset,
                        icmpv6_len,
                        neighbor_handler,
                        pmtu,
                        now,
                        self.rx_offload,
                        self.tx_offload,
                        rx_return,
                        tx_return,
                    );
                }
                IpProtocols::Udp => {
                    udp_handler.process_ipv6(frame, None, payload_offset, rx_return);
                }
                IpProtocols::Tcp => {
                    tcp_handler.process_ipv6(frame, payload_offset, now, neighbor_handler, free_frames, rx_return, tx_return);
                }
                _ => {
                    // RFC 4443 §3.4: send Parameter Problem (code 1) with
                    // pointer to the unrecognized Next Header field.
                    let pointer = (next_header_offset - eth_len) as u32;
                    icmpv6::send_icmpv6_error(
                        frame,
                        Icmpv6Types::ParameterProblem,
                        Icmpv6Codes::UnrecognizedNextHeader,
                        pointer.to_be_bytes(),
                        protocol,
                        payload_offset,
                        self.tx_offload,
                        rx_return,
                        tx_return,
                    );
                }
            },
            NextHeaderResult::Fragment { offset } => {
                let frag_next_header = frame[offset];
                if frag_next_header == IpProtocols::Udp {
                    udp_handler.process_ipv6(frame, Some(offset), 0, rx_return);
                } else if frag_next_header == IpProtocols::Tcp {
                    self.ipv6_tcp_fragments_dropped += 1;
                    rx_return.push(frame);
                } else {
                    rx_return.push(frame);
                }
            }
            NextHeaderResult::Malformed | NextHeaderResult::NoPayload => {
                rx_return.push(frame);
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use coarsetime::Duration;

    use crate::{
        net::{
            checksum::{compute_icmpv6_checksum, compute_udp_checksum_v6},
            handler::{tcp::TcpHandler, udp::UdpHandler},
            wire::{
                ip::{IpAddress, Ipv6Address},
                udp::UDP_HEADER_LEN,
            },
        },
        xdp::frame::BasicFrameBuffer,
    };

    use super::*;

    const REMOTE_IP: Ipv6Address =
        Ipv6Address::new([0xFE, 0x80, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2]);
    const LOCAL_IP: Ipv6Address =
        Ipv6Address::new([0xFE, 0x80, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]);

    fn new_handler() -> Ipv6Handler {
        Ipv6Handler::new(false, false)
    }

    fn new_neighbor_handler() -> NeighborHandler {
        NeighborHandler::new("test0", Duration::from_secs(60)).unwrap()
    }

    fn new_udp_handler<'umem>() -> UdpHandler<'umem> {
        UdpHandler::new(256, false)
    }

    fn new_tcp_handler() -> TcpHandler {
        TcpHandler::new(false, false)
    }

    /// Builds a valid Ethernet + IPv6 frame with no extension headers.
    fn build_ipv6_frame(
        src: Ipv6Address,
        dst: Ipv6Address,
        next_header: u8,
        hop_limit: u8,
        payload: &[u8],
    ) -> Vec<u8> {
        let eth_len = size_of::<EthernetFrame>();
        let payload_len = payload.len() as u16;
        let mut buf = vec![0u8; eth_len + IPV6_HEADER_LEN + payload.len()];

        buf[12] = 0x86;
        buf[13] = 0xDD;

        let ip = &mut buf[14..];
        ip[0] = 0x60;
        ip[4..6].copy_from_slice(&payload_len.to_be_bytes());
        ip[6] = next_header;
        ip[7] = hop_limit;
        let src_bytes: [u8; 16] = src.into();
        ip[8..24].copy_from_slice(&src_bytes);
        let dst_bytes: [u8; 16] = dst.into();
        ip[24..40].copy_from_slice(&dst_bytes);

        buf[eth_len + IPV6_HEADER_LEN..].copy_from_slice(payload);
        buf
    }

    /// Builds an IPv6 frame with a Hop-by-Hop extension header.
    fn build_ipv6_with_ext_header(
        src: Ipv6Address,
        dst: Ipv6Address,
        upper_protocol: u8,
        hop_limit: u8,
        payload: &[u8],
    ) -> Vec<u8> {
        let eth_len = size_of::<EthernetFrame>();
        let ext_len = 8;
        let payload_len = (ext_len + payload.len()) as u16;
        let mut buf = vec![0u8; eth_len + IPV6_HEADER_LEN + ext_len + payload.len()];

        buf[12] = 0x86;
        buf[13] = 0xDD;

        let ip = &mut buf[14..];
        ip[0] = 0x60;
        ip[4..6].copy_from_slice(&payload_len.to_be_bytes());
        ip[6] = EXT_HOP_BY_HOP;
        ip[7] = hop_limit;
        let src_bytes: [u8; 16] = src.into();
        ip[8..24].copy_from_slice(&src_bytes);
        let dst_bytes: [u8; 16] = dst.into();
        ip[24..40].copy_from_slice(&dst_bytes);

        let ext_offset = eth_len + IPV6_HEADER_LEN;
        buf[ext_offset] = upper_protocol;
        buf[ext_offset + 1] = 0;

        buf[ext_offset + ext_len..].copy_from_slice(payload);
        buf
    }

    /// Builds an IPv6 frame with a Fragment extension header.
    fn build_ipv6_with_fragment(
        src: Ipv6Address,
        dst: Ipv6Address,
        upper_protocol: u8,
        frag_offset: u16,
        more_fragments: bool,
        payload: &[u8],
    ) -> Vec<u8> {
        let eth_len = size_of::<EthernetFrame>();
        let payload_len = (FRAGMENT_EXT_LEN + payload.len()) as u16;
        let mut buf = vec![0u8; eth_len + IPV6_HEADER_LEN + FRAGMENT_EXT_LEN + payload.len()];

        buf[12] = 0x86;
        buf[13] = 0xDD;

        let ip = &mut buf[14..];
        ip[0] = 0x60;
        ip[4..6].copy_from_slice(&payload_len.to_be_bytes());
        ip[6] = EXT_FRAGMENT;
        ip[7] = 64;
        let src_bytes: [u8; 16] = src.into();
        ip[8..24].copy_from_slice(&src_bytes);
        let dst_bytes: [u8; 16] = dst.into();
        ip[24..40].copy_from_slice(&dst_bytes);

        let frag_offset_raw = eth_len + IPV6_HEADER_LEN;
        buf[frag_offset_raw] = upper_protocol;
        buf[frag_offset_raw + 1] = 0;
        let fo_m = (frag_offset << 3) | (if more_fragments { 1 } else { 0 });
        buf[frag_offset_raw + 2..frag_offset_raw + 4].copy_from_slice(&fo_m.to_be_bytes());

        buf[frag_offset_raw + FRAGMENT_EXT_LEN..].copy_from_slice(payload);
        buf
    }

    #[test]
    fn walk_no_extensions() {
        let buf = build_ipv6_frame(REMOTE_IP, LOCAL_IP, IpProtocols::Udp, 64, &[0; 8]);
        let eth_len = size_of::<EthernetFrame>();
        let start = eth_len + IPV6_HEADER_LEN;
        let nh_offset = eth_len + 6;

        match walk_extension_headers(&buf, IpProtocols::Udp, start, nh_offset) {
            NextHeaderResult::Protocol {
                protocol,
                payload_offset,
                next_header_offset,
            } => {
                assert_eq!(protocol, IpProtocols::Udp);
                assert_eq!(payload_offset, start);
                assert_eq!(next_header_offset, nh_offset);
            }
            _ => panic!("expected Protocol"),
        }
    }

    #[test]
    fn walk_hop_by_hop_extension() {
        let buf = build_ipv6_with_ext_header(REMOTE_IP, LOCAL_IP, IpProtocols::Tcp, 64, &[0; 20]);
        let eth_len = size_of::<EthernetFrame>();
        let start = eth_len + IPV6_HEADER_LEN;
        let nh_offset = eth_len + 6;

        match walk_extension_headers(&buf, EXT_HOP_BY_HOP, start, nh_offset) {
            NextHeaderResult::Protocol {
                protocol,
                payload_offset,
                next_header_offset,
            } => {
                assert_eq!(protocol, IpProtocols::Tcp);
                assert_eq!(payload_offset, start + 8);
                assert_eq!(next_header_offset, start);
            }
            _ => panic!("expected Protocol"),
        }
    }

    #[test]
    fn walk_fragment_returns_fragment() {
        let buf = build_ipv6_with_fragment(REMOTE_IP, LOCAL_IP, IpProtocols::Udp, 0, true, &[0; 8]);
        let eth_len = size_of::<EthernetFrame>();
        let start = eth_len + IPV6_HEADER_LEN;

        match walk_extension_headers(&buf, EXT_FRAGMENT, start, eth_len + 6) {
            NextHeaderResult::Fragment { offset } => {
                assert_eq!(offset, start);
            }
            _ => panic!("expected Fragment"),
        }
    }

    #[test]
    fn walk_no_next_header() {
        let buf = build_ipv6_frame(REMOTE_IP, LOCAL_IP, NO_NEXT_HEADER, 64, &[]);
        let eth_len = size_of::<EthernetFrame>();
        let start = eth_len + IPV6_HEADER_LEN;

        match walk_extension_headers(&buf, NO_NEXT_HEADER, start, eth_len + 6) {
            NextHeaderResult::NoPayload => {}
            _ => panic!("expected NoPayload"),
        }
    }

    #[test]
    fn walk_truncated_extension_is_malformed() {
        let eth_len = size_of::<EthernetFrame>();
        let mut buf = vec![0u8; eth_len + IPV6_HEADER_LEN + 2];
        buf[12] = 0x86;
        buf[13] = 0xDD;
        buf[14] = 0x60;
        buf[18..20].copy_from_slice(&2u16.to_be_bytes());
        buf[20] = EXT_HOP_BY_HOP;
        buf[21] = 64;

        let ext_start = eth_len + IPV6_HEADER_LEN;
        buf[ext_start] = IpProtocols::Udp;
        buf[ext_start + 1] = 0; // Hdr Ext Len = 0 means 8 bytes, but only 2 available

        match walk_extension_headers(&buf, EXT_HOP_BY_HOP, ext_start, eth_len + 6) {
            NextHeaderResult::Malformed => {}
            _ => panic!("expected Malformed"),
        }
    }

    #[test]
    fn walk_exceeds_max_extensions_is_malformed() {
        // Build a chain of 17 Hop-by-Hop extension headers (exceeds MAX_EXT_HEADERS=16).
        let eth_len = size_of::<EthernetFrame>();
        let ext_count = 17;
        let ext_size = 8; // each ext header is 8 bytes (Hdr Ext Len = 0)
        let total_ext = ext_count * ext_size;
        let mut buf = vec![0u8; eth_len + IPV6_HEADER_LEN + total_ext];

        buf[12] = 0x86;
        buf[13] = 0xDD;
        buf[14] = 0x60;
        buf[18..20].copy_from_slice(&(total_ext as u16).to_be_bytes());
        buf[20] = EXT_HOP_BY_HOP;
        buf[21] = 64;

        let ext_start = eth_len + IPV6_HEADER_LEN;
        for i in 0..ext_count {
            let off = ext_start + i * ext_size;
            // Each points to Hop-by-Hop (0) as next header, except the last
            // which points to UDP (but we'll never reach it).
            buf[off] = if i < ext_count - 1 {
                EXT_HOP_BY_HOP
            } else {
                IpProtocols::Udp
            };
            buf[off + 1] = 0; // Hdr Ext Len = 0 -> 8 bytes
        }

        match walk_extension_headers(&buf, EXT_HOP_BY_HOP, ext_start, eth_len + 6) {
            NextHeaderResult::Malformed => {}
            _ => panic!("expected Malformed for excessive extension headers"),
        }
    }

    #[test]
    fn frame_too_short_goes_to_rx() {
        let mut data = [0u8; 50];

        let mut handler = new_handler();
        let nh = new_neighbor_handler();
        let mut udp = new_udp_handler();
        let mut tcp = new_tcp_handler();
        let mut rx = BasicFrameBuffer::new(4);
        let mut tx = BasicFrameBuffer::new(4);

        let frame = Frame::new(0, &mut data, 50, false);

        handler.handle(
            frame,
            &nh,
            &mut udp,
            &mut tcp,
            &PmtuCache::new(),
            Instant::now(),
            &mut BasicFrameBuffer::new(4),
            &mut rx,
            &mut tx,
        );
        assert_eq!(rx.num_frames(), 1);
        assert_eq!(tx.num_frames(), 0);
    }

    #[test]
    fn wrong_version_goes_to_rx() {
        let mut data = build_ipv6_frame(REMOTE_IP, LOCAL_IP, IpProtocols::Udp, 64, &[0; 8]);
        data[14] = (data[14] & 0x0F) | 0x40; // version 4 instead of 6

        let mut handler = new_handler();
        let nh = new_neighbor_handler();
        let mut udp = new_udp_handler();
        let mut tcp = new_tcp_handler();
        let mut rx = BasicFrameBuffer::new(4);
        let mut tx = BasicFrameBuffer::new(4);

        let len = data.len();
        let frame = Frame::new(0, &mut data, len, false);

        handler.handle(
            frame,
            &nh,
            &mut udp,
            &mut tcp,
            &PmtuCache::new(),
            Instant::now(),
            &mut BasicFrameBuffer::new(4),
            &mut rx,
            &mut tx,
        );
        assert_eq!(rx.num_frames(), 1);
        assert_eq!(tx.num_frames(), 0);
    }

    #[test]
    fn payload_shorter_than_claimed_goes_to_rx() {
        // Build a frame with only 8 bytes payload but claim 100 in payload_length
        let mut data = build_ipv6_frame(REMOTE_IP, LOCAL_IP, IpProtocols::Udp, 64, &[0; 8]);
        data[18] = 0x00;
        data[19] = 100; // claim 100 bytes but only 8 available

        let mut handler = new_handler();
        let nh = new_neighbor_handler();
        let mut udp = new_udp_handler();
        let mut tcp = new_tcp_handler();
        let mut rx = BasicFrameBuffer::new(4);
        let mut tx = BasicFrameBuffer::new(4);

        let len = data.len();
        let frame = Frame::new(0, &mut data, len, false);

        handler.handle(
            frame,
            &nh,
            &mut udp,
            &mut tcp,
            &PmtuCache::new(),
            Instant::now(),
            &mut BasicFrameBuffer::new(4),
            &mut rx,
            &mut tx,
        );
        assert_eq!(rx.num_frames(), 1);
        assert_eq!(tx.num_frames(), 0);
    }

    #[test]
    fn fragment_goes_to_udp_handler() {
        let mut data =
            build_ipv6_with_fragment(REMOTE_IP, LOCAL_IP, IpProtocols::Udp, 0, true, &[0; 8]);

        let mut handler = new_handler();
        let nh = new_neighbor_handler();
        let mut udp = new_udp_handler();
        let mut tcp = new_tcp_handler();
        let mut rx = BasicFrameBuffer::new(4);
        let mut tx = BasicFrameBuffer::new(4);

        let len = data.len();
        let frame = Frame::new(0, &mut data, len, false);

        handler.handle(
            frame,
            &nh,
            &mut udp,
            &mut tcp,
            &PmtuCache::new(),
            Instant::now(),
            &mut BasicFrameBuffer::new(4),
            &mut rx,
            &mut tx,
        );
        assert_eq!(rx.num_frames(), 0);
        assert_eq!(tx.num_frames(), 0);
        assert_eq!(udp.pending_reassembly(), 1);
    }

    #[test]
    fn non_udp_fragment_goes_to_rx() {
        let mut data =
            build_ipv6_with_fragment(REMOTE_IP, LOCAL_IP, IpProtocols::Tcp, 0, true, &[0; 20]);

        let mut handler = new_handler();
        let nh = new_neighbor_handler();
        let mut udp = new_udp_handler();
        let mut tcp = new_tcp_handler();
        let mut rx = BasicFrameBuffer::new(4);
        let mut tx = BasicFrameBuffer::new(4);

        let len = data.len();
        let frame = Frame::new(0, &mut data, len, false);

        handler.handle(
            frame,
            &nh,
            &mut udp,
            &mut tcp,
            &PmtuCache::new(),
            Instant::now(),
            &mut BasicFrameBuffer::new(4),
            &mut rx,
            &mut tx,
        );
        assert_eq!(rx.num_frames(), 1);
        assert_eq!(tx.num_frames(), 0);
    }

    #[test]
    fn icmpv6_echo_request_generates_reply() {
        let eth_len = size_of::<EthernetFrame>();
        let icmpv6_len = 16;
        let frame_len = eth_len + IPV6_HEADER_LEN + icmpv6_len;
        let mut data = vec![0u8; 512];

        data[12] = 0x86;
        data[13] = 0xDD;
        data[14] = 0x60;
        data[18..20].copy_from_slice(&(icmpv6_len as u16).to_be_bytes());
        data[20] = IpProtocols::IcmpV6;
        data[21] = 64;
        let src_bytes: [u8; 16] = REMOTE_IP.into();
        data[22..38].copy_from_slice(&src_bytes);
        let dst_bytes: [u8; 16] = LOCAL_IP.into();
        data[38..54].copy_from_slice(&dst_bytes);

        let icmp_off = eth_len + IPV6_HEADER_LEN;
        data[icmp_off] = Icmpv6Types::EchoRequest;
        let cksum = compute_icmpv6_checksum(
            &REMOTE_IP,
            &LOCAL_IP,
            &data[icmp_off..icmp_off + icmpv6_len],
        );
        data[icmp_off + 2] = cksum[0];
        data[icmp_off + 3] = cksum[1];

        let mut handler = new_handler();
        let nh = new_neighbor_handler();
        let mut udp = new_udp_handler();
        let mut tcp = new_tcp_handler();
        let mut rx = BasicFrameBuffer::new(4);
        let mut tx = BasicFrameBuffer::new(4);

        let frame = Frame::new(0, &mut data, frame_len, false);
        handler.handle(
            frame,
            &nh,
            &mut udp,
            &mut tcp,
            &PmtuCache::new(),
            Instant::now(),
            &mut BasicFrameBuffer::new(4),
            &mut rx,
            &mut tx,
        );

        assert_eq!(rx.num_frames(), 0);
        assert_eq!(tx.num_frames(), 1);
    }

    #[test]
    fn unknown_protocol_sends_parameter_problem() {
        let raw = build_ipv6_frame(REMOTE_IP, LOCAL_IP, 255, 64, &[0; 8]);
        let mut data = vec![0u8; 2048];
        data[..raw.len()].copy_from_slice(&raw);

        let mut handler = new_handler();
        let nh = new_neighbor_handler();
        let mut udp = new_udp_handler();
        let mut tcp = new_tcp_handler();
        let mut rx = BasicFrameBuffer::new(4);
        let mut tx = BasicFrameBuffer::new(4);

        let frame = Frame::new(0, &mut data, raw.len(), false);

        handler.handle(
            frame,
            &nh,
            &mut udp,
            &mut tcp,
            &PmtuCache::new(),
            Instant::now(),
            &mut BasicFrameBuffer::new(4),
            &mut rx,
            &mut tx,
        );
        assert_eq!(rx.num_frames(), 0);
        assert_eq!(tx.num_frames(), 1);
    }

    #[test]
    fn no_next_header_goes_to_rx() {
        let mut data = build_ipv6_frame(REMOTE_IP, LOCAL_IP, NO_NEXT_HEADER, 64, &[]);

        let mut handler = new_handler();
        let nh = new_neighbor_handler();
        let mut udp = new_udp_handler();
        let mut tcp = new_tcp_handler();
        let mut rx = BasicFrameBuffer::new(4);
        let mut tx = BasicFrameBuffer::new(4);

        let len = data.len();
        let frame = Frame::new(0, &mut data, len, false);

        handler.handle(
            frame,
            &nh,
            &mut udp,
            &mut tcp,
            &PmtuCache::new(),
            Instant::now(),
            &mut BasicFrameBuffer::new(4),
            &mut rx,
            &mut tx,
        );
        assert_eq!(rx.num_frames(), 1);
        assert_eq!(tx.num_frames(), 0);
    }

    #[test]
    fn malformed_extension_goes_to_rx() {
        // Build frame with Hop-by-Hop next header but only 2 bytes of ext header data
        // (claims to need 8 bytes via Hdr Ext Len=0).
        let eth_len = size_of::<EthernetFrame>();
        let mut data = vec![0u8; eth_len + IPV6_HEADER_LEN + 2];
        data[12] = 0x86;
        data[13] = 0xDD;
        data[14] = 0x60;
        data[18..20].copy_from_slice(&2u16.to_be_bytes());
        data[20] = EXT_HOP_BY_HOP;
        data[21] = 64;

        let ext_start = eth_len + IPV6_HEADER_LEN;
        data[ext_start] = IpProtocols::Udp;
        data[ext_start + 1] = 0;

        let mut handler = new_handler();
        let nh = new_neighbor_handler();
        let mut udp = new_udp_handler();
        let mut tcp = new_tcp_handler();
        let mut rx = BasicFrameBuffer::new(4);
        let mut tx = BasicFrameBuffer::new(4);

        let len = data.len();
        let frame = Frame::new(0, &mut data, len, false);

        handler.handle(
            frame,
            &nh,
            &mut udp,
            &mut tcp,
            &PmtuCache::new(),
            Instant::now(),
            &mut BasicFrameBuffer::new(4),
            &mut rx,
            &mut tx,
        );
        assert_eq!(rx.num_frames(), 1);
        assert_eq!(tx.num_frames(), 0);
    }

    #[test]
    fn valid_udp_routed_to_socket() {
        let eth_len = size_of::<EthernetFrame>();
        let udp_len = UDP_HEADER_LEN;
        let payload_len = udp_len as u16;
        let frame_len = eth_len + IPV6_HEADER_LEN + udp_len;
        let mut data = vec![0u8; frame_len];

        data[12] = 0x86;
        data[13] = 0xDD;
        data[14] = 0x60;
        data[18..20].copy_from_slice(&payload_len.to_be_bytes());
        data[20] = IpProtocols::Udp;
        data[21] = 64;
        let src_bytes: [u8; 16] = REMOTE_IP.into();
        data[22..38].copy_from_slice(&src_bytes);
        let dst_bytes: [u8; 16] = LOCAL_IP.into();
        data[38..54].copy_from_slice(&dst_bytes);

        let udp_off = eth_len + IPV6_HEADER_LEN;
        data[udp_off + 4..udp_off + 6].copy_from_slice(&(udp_len as u16).to_be_bytes());
        let cksum = compute_udp_checksum_v6(&REMOTE_IP, &LOCAL_IP, &data[udp_off..frame_len]);
        data[udp_off + 6] = cksum[0];
        data[udp_off + 7] = cksum[1];

        let mut handler = new_handler();
        let nh = new_neighbor_handler();
        let mut udp = UdpHandler::new(256, false);
        let rx_queue = udp.bind(IpAddress::V6(LOCAL_IP), 0, 256).unwrap();
        let mut tcp = new_tcp_handler();
        let mut rx = BasicFrameBuffer::new(4);
        let mut tx = BasicFrameBuffer::new(4);

        let frame = Frame::new(0, &mut data, frame_len, false);
        handler.handle(
            frame,
            &nh,
            &mut udp,
            &mut tcp,
            &PmtuCache::new(),
            Instant::now(),
            &mut BasicFrameBuffer::new(4),
            &mut rx,
            &mut tx,
        );

        assert_eq!(rx.num_frames(), 0);
        assert_eq!(tx.num_frames(), 0);
        assert_eq!(rx_queue.len(), 1);
    }
}
