name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-24.04
    steps:
    - name: Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-coverage-${{ hashFiles('**/Cargo.lock') }}
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libbpf-dev libelf-dev libpcap-dev libmnl-dev linux-headers-$(uname -r)
    - name: Install cargo-llvm-cov
      uses: taiki-e/install-action@cargo-llvm-cov
    - uses: actions/checkout@v5
      with:
        submodules: recursive
    - name: Run coverage report
      run: cargo llvm-cov --all-features --workspace --codecov --output-path codecov.json
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: codecov.json
        fail_ci_if_error: true
  build:
    name: Build/Compile
    runs-on: ubuntu-24.04
    steps:
    - name: Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-compile-${{ hashFiles('**/Cargo.lock') }}
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libbpf-dev libelf-dev libpcap-dev libmnl-dev linux-headers-$(uname -r)
    - name: Install cargo-llvm-cov
      uses: taiki-e/install-action@cargo-llvm-cov
    - uses: actions/checkout@v5
      with:
        submodules: recursive
    - name: Compile
      run: cargo build --all-features --workspace
